version: 1.1.{build}-{branch}



image:
 - Visual Studio 2019

platform:
  - x64
  # - x86
  # - amd64

init:
  - git config --global core.autocrlf input

stack: node 18.12.0

cache:
  - node_modules

install:
 - yarn

build: off


deploy: off

branches:
  only:
    - v1

artifacts:
  - path: '\dist/to/file.exe\'


after_build:
  - yarn run build
  - yarn run lint
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy_script:

# https://www.appveyor.com/docs/how-to/git-push/
# https://www.appveyor.com/docs/how-to/git-push/#adding-access-token-to-credential-store
  - git config --global credential.helper store
  - git config --global user.name Tryd0g0lik
  - git config --global user.email work80@mail.ru
  - ps: Write-Host "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials" -NoNewline

  - yarn add push-dir --dir=dist --branch=master --force --verbose

